pipeline {
    agent any

    environment {
        DOCKER_IMAGE = "shreyeah29/myapp:latest"
        KUBECONFIG = "/Users/sweety/.kube/config"
    }

    stages {
        stage('Checkout Code') {
            steps {
                git 'https://github.com/shreyeah29/jenkins.git'
            }
        }

        stage('Build Docker Image') {
            steps {
                sh 'docker build -t $DOCKER_IMAGE .'
            }
        }

        stage('Push to Docker Hub') {
            steps {
                withCredentials([usernamePassword(credentialsId: 'dockerhub-creds', usernameVariable: 'USER', passwordVariable: 'PASS')]) {
                    sh 'echo $PASS | docker login -u $USER --password-stdin'
                    sh 'docker push $DOCKER_IMAGE'
                }
            }
        }

        stage('Deploy to Kubernetes') {
            steps {
                sh 'kubectl apply -f deployment.yaml'
                sh 'kubectl apply -f service.yaml'
                sh 'kubectl get pods'
                sh 'kubectl get svc'
            }
        }
    }
}
